---
  .travis.yml:
    hc_secure: "X/2CI7xNlFxBmFCl8TXlPG62T9ldDKUIEf7AW5wt/3h1qLD8XmGmgxKqLmPJ\\nInjni1RWB4oA2BHy2zxtZFhbEUcFQKMWYIXSpsX4A48hxRa+h89LROtYlTtc\\nQAZQsdNsxyCn3+hIt+5uExX9EmPElmWw3i5n2K1WquoU6AtVep0="
